Feat/#8 마이페이지- 히스토리뷰
OWN-SIZE/onsize-website pull request #12
Opened 2023-01-02 15:02 UTC by borimong

## 이슈 넘버
- close #8

## 구현 사항

- [ ] 마이페이지-히스토리뷰 ui 구현 완료

## Need Review
- ~ 부분 이렇게 구현했어요, 피드백 부탁해요!

1. Layout 이용해서 헤더 붙여주고, Styled.Root 이름 이용해서 최상단 컨테이너를 만들어주었어요. 이때 width 값은 고정으로, margin: 0 auto 이용해서 가운데 정렬해 주었습니다!
![image](https://user-images.githubusercontent.com/86764406/210247722-1c6023a8-abb4-4305-a490-796862dab2c0.png)
2. 아래 스크린샷처럼 컴포넌트를 4개로 분리해서 차례대로 만들어주엇어요! UserInformationContainer, History, InformationContainer, UserStateManagementContainer 이렇게 네 개인데, 맨 마지막 컨테이너는 이름이 너무 길어서 좀 더 효율적인 이름으로 바꾸려고 생각 중이에요..!
3. 가운데 정렬은 모두 margin: 0 auto 사용했고, 공통적인 스타일은 자식 선택자 이용해서 최대한 묶었습니다!
![image](https://user-images.githubusercontent.com/86764406/210248547-d0c177a3-99ac-4cc8-8201-3004ed43347d.png)

## 📸 스크린샷

![image](https://user-images.githubusercontent.com/86764406/210246985-00cc76e2-9427-4570-b686-f167a01154d6.png)
![image](https://user-images.githubusercontent.com/86764406/210247020-83e0a776-f876-4288-b319-e302e09519b0.png)
![image](https://user-images.githubusercontent.com/86764406/210247046-643011aa-e5f7-42ff-b722-c4b26fa78b04.png)
![image](https://user-images.githubusercontent.com/86764406/210247074-1f658893-1819-4165-afd9-57855d425337.png)

## Reference

2023-01-03 03:17 UTC, ilmerry approved these changes

2023-01-03 03:17 UTC, ilmerry commented on styles/theme.ts
> +  body6: FONT({ weight: 500, size: 2.6, lineHeight: 3.5 }),
폰트 추가됐나보구나!! 굳굳 고마워

2023-01-03 03:17 UTC, ilmerry commented on pages/mypage/index.tsx
> +            placeholder="blur"
나 `placeholder="blur"` 넣는거 깜빡했다! 현수덕분에 리마인드:)

2023-01-03 04:56 UTC, leeseooo requested changes

2023-01-03 04:56 UTC, leeseooo commented on pages/mypage/index.tsx
> +            placeholder="blur"
이미지 최적화 굿굿!

2023-01-03 04:56 UTC, leeseooo commented on styles/theme.ts
> +  body6: FONT({ weight: 500, size: 2.6, lineHeight: 3.5 }),
폰트 세팅 굿~~

2023-01-03 04:56 UTC, leeseooo commented on pages/mypage/index.tsx
> +import profileDefault from 'assets/icon/profileDefault.png';
아이콘이나 이미지는 용량이랑 픽셀깨짐 이슈가 있어서 불가피한 경우 제외하고는 svg로 받아주라

2023-01-04 04:25 UTC, leeseooo approved these changes

2023-01-04 07:00 UTC, merged