Feat/#7
OWN-SIZE/onsize-website pull request #15
Opened 2023-01-04 04:22 UTC by seobbang

## 이슈 넘버
- close #7

## 구현 사항
- [x] home_처음 UI 구현
- [x] home_메인 UI 구현

## Problem
* svg, ReactComponent 이슈로 우선 오류 있기 전에 단순 UI만 짜서 commit 했던 부분들만 push 하고, 그 이후 부분은 다른 브랜치로 분리하려고 합니다.
* 새로운 라이브러리 깔면서 전체적으로 꼬인 것 같아요 ㅠ uninstall해도 안 먹히는 것을 보니..! 그래서 분리 했어요.

## Need Review

## 📸 스크린샷
1. home_처음 구현
![image](https://user-images.githubusercontent.com/97084864/210484072-b46fe5a7-7617-4282-a433-7aed72b82d9b.png)

2. home_메인  UI 구현
![image](https://user-images.githubusercontent.com/97084864/210483952-68369f2e-618c-460a-9009-b696ce49c59f.png)

2023-01-04 08:49 UTC, leeseooo requested changes

2023-01-04 08:49 UTC, leeseooo commented on components/home/HomeFirst.tsx
> +    </Styled.Container>
컨벤션으로 최상위 태그는 Root로 쓰기로 했어!

2023-01-04 08:49 UTC, leeseooo commented on components/home/HomeMain.tsx
> +export default function HomeMain() {
컨벤션으로 function HomeMain(){} 쓰고 하단에 export default HomeMain 하기로 했어!
rfce 단축키 쓰면 편할겨

2023-01-04 08:49 UTC, leeseooo commented on components/home/HoverIcon.tsx
> +  const [iconHovered, setIconHovered] = useState('');
딱 봤을 때 이게 초기화는 string인데 네이밍은 boolean 같아서 혼란스러운 것 같아요.
변수명을 바꿔보는 건 어떨까요?

2023-01-04 08:49 UTC, leeseooo commented on components/home/HoverIcon.tsx
> +    <div>
이것도 Styled.Root로 바꿔주면 좋을듯

2023-01-04 08:49 UTC, leeseooo commented on components/home/HoverIcon.tsx
> +          <Image src={PinButtonFillIcon} alt="고정 해제 버튼 아이콘" />
alt 속성을 자세하게 써줘서 좋다 👍

2023-01-04 08:51 UTC, seobbang commented on components/home/HomeFirst.tsx
> +    </Styled.Container>
요거 HomeLading 안에 들어가는데도 그런거였구나 ㅋㅋㅋㅋ아직도 이해 못했네

2023-01-04 08:52 UTC, seobbang commented on components/home/HomeMain.tsx
> +export default function HomeMain() {
holy shit.. rfc`e`였어.....

2023-01-04 08:52 UTC, seobbang commented on components/home/HoverIcon.tsx
> +  const [iconHovered, setIconHovered] = useState('');
오 알겠씁니당 !!

2023-01-05 02:41 UTC, ilmerry approved these changes
컴포넌트들 잘 분리해서 깔끔하게 잘 짰다!! 너무 수고많았어~~ 좀만더 화이팅!

2023-01-05 02:41 UTC, ilmerry commented on components/home/HoverIcon.tsx
> +          )}
반복되는 코드가 많은 것 같아서! 분기처리를 Image src에만 해줘도 괜찮지 않을까?
```tsx
<Image src={data.isPin ? PinButtonFillIcon : PinButonIcon} alt="고정 버튼 아이콘" />
```
이런식으로!

2023-01-05 02:41 UTC, ilmerry commented on components/home/Product.tsx
> +  const [imgHoveredTarget, setImgHoveredTarget] = useState('');
useState를 쓸때 타입을 명시해주면 좀 더 좋은 코드가 될 것 같아!
`const [imgHoveredTarget, setImgHoveredTarget] = useState<string>('');`

2023-01-05 05:08 UTC, leeseooo approved these changes

2023-01-05 05:08 UTC, leeseooo commented on components/home/Product.tsx
> +  const [imgHoveredTarget, setImgHoveredTarget] = useState('');
근데 타입스크립트가 자동으로 추론할 수 있는 원시타입은 굳이 명시하지 않아도 된다고 생각혀
string이나 number, boolean같은건?
물론 변수 네이밍을 잘 지었다는 가정 하에 .. ㅎ

2023-01-05 08:22 UTC, seobbang commented on components/home/Product.tsx
> +  const [imgHoveredTarget, setImgHoveredTarget] = useState('');
오 마쟈 나도 원래 useState에 타입 지정 다 했었는데, 그 이번에 개발 전에 공부할 때 보니까 useState를 그냥 쓸 때는 자동 추론이라 굳이 쓰지 않아도 된다고 하더라!
대신 막 객체가 들어가거나 그런 경우에 쓰라고 했던거같앙

2023-01-05 08:22 UTC, seobbang commented on components/home/HoverIcon.tsx
> +          )}
와 나 왜 이 생각을 못했지? 너무 좋다 고마어 은형 ❤

2023-01-06 05:33 UTC, merged